### PR TITLE
Pixi: Fully reset loading UI between runs

### LINKED ISSUE #4478: Pixi: status colors should be reset between runs
if you scan a failing url, then scan a good one, the visual results are confusing

image

### PR DESCRIPTION
**Pull request by caroqliu**
- Resets colors of performance summaries
- Fixes bug in filter UI resetting

Fixes #4478

### CODE REVIEW

File: pixi/src/ui/recommendations/RecommendationsView.js [hunk 1]
```diff
@@ -39,8 +39,9 @@ export default class RecommendationsView {
       this.container.removeChild(items[i]);
     }
 
-    for (let i = 1; i < this.filter.children.length; i++) {
-      this.filter.removeChild(this.filterPills[i]);
+    const length = this.filter.children.length;
```
Comment (patrickkettner) [inline pixi/src/ui/recommendations/RecommendationsView.js:42]: Any chance filter would be undefined?

File: pixi/src/ui/report/CoreWebVitalsReportView.js [hunk 2]
```diff
@@ -134,7 +134,7 @@ class CoreWebVitalView {
   }
 
   reset() {
-    this.container.classList.remove(...Object.values(CATEGORIES));
+    this.container.classList.remove(...Object.keys(CATEGORIES));
```
Comment (patrickkettner) [inline pixi/src/ui/report/CoreWebVitalsReportView.js:137]: At one point removing multiple classes at once didn't work and worker-dom, I'm assuming this was fixed?

File: pixi/src/ui/recommendations/RecommendationsView.js (hunk 1 above)
Comment (caroqliu) [reply pixi/src/ui/recommendations/RecommendationsView.js:42]: Not unless it gets removed from the j2 fragment, but as it stands it's always defined on construction of this class.

**Review by patrickkettner — APPROVED** [review]
