### PR TITLE
♻️ Pixi - Refactor input bar + add error label

### LINKED ISSUE #4334: `Enter` should submit the form
1. Go to https://amp-dev-staging.appspot.com/page-experience/
2. Type `https://amp.dev` 
3. Press Enter

Observation: Nothing happens
Expected: Tests should run, as if user clicked "Analyze"

### LINKED ISSUE #4335: Surface URL validation status on page
1. Go to https://amp-dev-staging.appspot.com/page-experience/
2. Type in "asd"
3. Click "Analyze"

Observation: Nothing happens (note in console there is the error: `Please enter a valid URL`
Expected: User should be notified that the URL is invalid. One option is to mimic validator.amp.dev: 
image

### PR DESCRIPTION
**Pull request by robinvanopstal**
Fixes #4335, Fixes #4334

### CODE REVIEW

File: pixi/src/ui/InputBar.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    this.container.classList.toggle('error', force);
+    this.label.textContent = error;
+  }
+
+  toggleLoading(force) {
+    this.submit.classList.toggle('loading', force);
+  }
+
+  get value() {
+    if (this.field.value) {
```
Comment (matthiasrohmer) [inline pixi/src/ui/InputBar.js:50]: Prefix with `http://` if no protocol is specified by the user

**Review by matthiasrohmer — COMMENTED** [review]
Looks good so far. Only one comment and the changes we discussed offline.

**Review by matthiasrohmer — APPROVED** [review]
Looks good from my side, forwarding to @caroqliu.

**Review by matthiasrohmer — CHANGES_REQUESTED** [review]
Protocol prefixing is waiting for tomorrow 🙂

File: pixi/src/ui/InputBar.js (hunk 1 above)
Comment (caroqliu) [reply pixi/src/ui/InputBar.js:50]: I thought we wanted to look for redirects?

File: frontend/scss/_mixins.scss [hunk 2]
```diff
@@ -165,6 +165,7 @@ box-shadow: 0 25px 50px 0 rgba(0,0,0,0.21);
     width: 45px;
     height: 45px;
     margin: 100px auto auto auto;
+    padding: 1px;
```
Comment (caroqliu) [inline frontend/scss/_mixins.scss:168]: Is this necessary?

File: pixi/src/ui/InputBar.js [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+export default class InputBar {
+  constructor(doc, callback) {
+    this.container = doc.getElementById('input-bar');
+    this.field = this.container.querySelector('#input-field');
+    this.submit = this.container.querySelector('#input-submit');
+    this.label = this.container.querySelector('label');
+
+    this.submit.addEventListener('click', callback);
+    this.field.addEventListener('keydown', (e) => {
+      if (e.keyCode == 13) {
```
Comment (caroqliu) [inline pixi/src/ui/InputBar.js:24]: Let's also have a flag that checks if it is already processing, otherwise the user can spam `Enter` to send lots of requests.

File: pixi/src/ui/InputBar.js [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+        callback();
+      }
+    });
+  }
+
+  async isValid() {
+    const pageUrl = await this.value;
+    try {
+      const url = new URL(pageUrl);
+      return url.protocol === 'http:' || url.protocol === 'https:';
```
Comment (caroqliu) [inline pixi/src/ui/InputBar.js:34]: This passes `http:asdf`, we should also check `url.hostname.split(".").length > 1`

File: pixi/src/ui/PageExperience.js [hunk 5]
```diff
@@ -39,38 +36,28 @@ export default class PageExperience {
...
+      pageUrl = await this.inputBar.value;
+    } catch (e) {
+      inputBar.toggleInputError(true, e);
     }
 
-    if (!this.isValidURL(pageUrl)) {
+    if (!(await this.inputBar.isValid())) {
       this.toggleLoading(false);
-      throw new Error('Please enter a valid URL');
+      this.inputBar.toggleError(true, 'Please enter a valid URL');
```
Comment (caroqliu) [inline pixi/src/ui/PageExperience.js:55]: Can the error message also be localizable?

File: frontend/scss/_mixins.scss (hunk 2 above)
Comment (robinvanopstal) [reply frontend/scss/_mixins.scss:168]: This will remove sharp edges

**Review by matthiasrohmer — APPROVED** [review]
